### ISSUE TITLE
feature request: undeploy VMs

### ISSUE THREAD

**Issue by sspreitzer** [oVirt/ovirt-ansible-vm-infra#13]
Hi

Thanks for this very nice ansible module. For my CI/CD testing I would like to destroy VMs and spin them up again. It would be a charm if your module would support a runmode like "undeploy" or "destroy" globally and/or VM wise.

Thank you very much
Sascha

**Comment by KKoukiou** [comment]
@sspreitzer thanks for using the role.  What do you mean by `undeploy`? Also by `globally and/or VM wise`?
If what you need is supporting absent VM state for the VMs I don't have anything against implementing this functionality in this role but why not using directly `ovirt_vms` module [1] for making VMs absent?

@machacekondra WDYT?

[1]
``` yaml
# Remove VM, if VM is running it will be stopped:
ovirt_vms:
    state: absent
    name: myvm
```
