### ISSUE TITLE
Is the example in the README correct?

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-ansible-vm-infra#21]
We defined 2 Apache VMs and one PG, but the affinity setting is for two PG VMs?

**Comment by mykaul** [comment]
@machacekondra  , @mwperina  ?

**Comment by machacekondra** [comment]
As far as I can see there are two PG vms, and they have nagative affinity, it seems OK to me.
```yaml

    vms:
      - name: postgresql-vm-0
        tag: postgresql_vm
        profile: "{{ db_vm }}"
      - name: postgresql-vm-1
        tag: postgresql_vm
        profile: "{{ db_vm }}"
      - name: apache-vm
        tag: httpd_vm
        profile: "{{ httpd_vm }}"

    affinity_groups:
      - name: db-ag
        cluster: production
        vm_enforcing: true
        vm_rule: negative
        vms:
          - postgresql-vm-0
          - postgresql-vm-1
```

**Comment by mykaul** [comment]
This is what I see in the README:
```
vms:
      - name: apache-vm-1
        tag: httpd
        profile: "{{ httpd_vm }}"
      - name: apache-vm-2
        tag: httpd
        profile: "{{ httpd_vm }}"
        state: stopped
      - name: postgresql-vm
        tag: db
        profile: "{{ db_vm }}"
```
