### ISSUE TITLE
feature request: Increase size of default disk

### ISSUE THREAD

**Issue by sspreitzer** [oVirt/ovirt-ansible-vm-infra#24]
Hi there

It would be nice to be able to increase the size of the default disk.
So that cloud-init could do its size increasing tricks.

Thank you and regards
Sascha

**Comment by ThomasADavis** [comment]
The issue is in the Ansible module - it's not capable of it from what I can tell.

**Comment by mykaul** [comment]
I'm not sure I understand the request and how it's related to cloud-init. Can you be more specific?

**Comment by sspreitzer** [comment]
@mykaul cloud-init is capable of resizing the FS if it sees the system disk is bigger than the root FS

**Comment by mykaul** [comment]
OK. But you can increase the size today, by passing the size parameter to the disk in the list?

**Comment by sspreitzer** [comment]
@ThomasADavis I don't think this is entirely true. I believe if you have VM name and disk name, you could enlarge the disk with ovirt_disk by giving a bigger than actual size. Reading the docs at http://docs.ansible.com/ansible/latest/modules/ovirt_disk_module.html#ovirt-disk-module it says: "Size of the disk. Size should be specified using IEC standard units. For example 10GiB, 1024MiB, etc.
Size can be only increased, not decreased."

**Comment by ThomasADavis** [comment]
The documentation is wrong for the ansible module.  However, it is true, you can only grow disks in ovirt; you cannot shrink them.

When I checked the ansible ovirt_disk module code it fails to update the disk size.  It never calls the disk_attachement_service.update with a newer provision size

Using this task:
```
  tasks:
    - name: upsize pew-pew's disk.
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: C74-1708-ovn_Disk1
        vm_name: test-resize
        size: 200GiB
        interface: virtio_scsi
        state: attached
```

gives this error:

```
[tdavis@gryphon ansible]$ ansible-playbook -i production_inventory.cfg --ask-vault vm-disk-resize.yml
Vault password: 

PLAY [disk change size] ******************************************************************************************************************************************

TASK [Login to oVirt] ********************************************************************************************************************************************
ok: [localhost]

TASK [upsize pew-pew's disk.] ************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Error: Fault reason is "Operation Failed". Fault detail is "[Cannot attach Virtual Disk. The disk is not shareable and is already attached to a VM.]". HTTP response code is 409.
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot attach Virtual Disk. The disk is not shareable and is already attached to a VM.]\". HTTP response code is 409."}
	to retry, use: --limit @/home/tdavis/ansible/vm-disk-resize.retry

PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

**Comment by machacekondra** [comment]
> When I checked the ansible ovirt_disk module code it fails to update the disk size. It never calls the disk_attachement_service.update with a newer provision size

Are you sure, you are not trying to attach that disk to different VM then it's already attached to?

**Comment by ThomasADavis** [comment]
changing from name to id (aka, uuid)

```
  tasks:
    - name: upsize pew-pew's disk.
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        id: aecf09cf-f691-4364-bd2d-de00b63761aa
        vm_name: test-resize
        size: 200GiB
        interface: virtio_scsi
        state: present

```

```
[tdavis@gryphon ansible]$ ansible-playbook -i production_inventory.cfg --ask-vault vm-disk-resize.yml
Vault password: 

PLAY [disk change size] *****************************************************************************************************************************************

TASK [Login to oVirt] *******************************************************************************************************************************************
ok: [localhost]

TASK [upsize pew-pew's disk.] ***********************************************************************************************************************************
changed: [localhost]

TASK [Logout from oVirt] ****************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ******************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   

```
works.  but getting the disk id is not easy in ansible.

and all or most of the vm's have the same disk name from the template in my case..

**Comment by machacekondra** [comment]
Currently we search only by disk name, and as you said there could be many with same name. So I will add to the search also the vm's name, if `vm_name` is passed.

**Comment by AlexGluck** [comment]
Vote up for this.

**Comment by AlexGluck** [comment]
Now i use this tasks: 
```
    - name: Try get disk info from VM
      ovirt_vms_facts:
        auth: "{{ ovirt_auth }}"
        pattern: name="{{ vm|replace('_', '-') }}.{{ vms[vm].dns_zone|default(default.dns_zone) }}"
        fetch_nested: true
        nested_attributes: disk
      register: disk_vm
      when: vms[vm].disk is defined
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm

    - name: Change disk size
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        id: "{{ item.1.ansible_facts.ovirt_vms[0].disk_attachments[0].disk.id }}"
        size: "{{ vms[item.0].disk }} GiB"
        vm_name: "{{ item.0|replace('_', '-') }}.{{ vms[item.0].dns_zone|default(default.dns_zone) }}"
        interface: virtio_scsi
        state: attached
      when: vms[item.0].disk is defined
      with_together:
        - "{{ vms }}"
        - "{{ disk_vm.results }}"
```

**Comment by DanielFroehlich** [comment]
I would like to come back to the original request, as I am facing the same inconvenience:
I do have a template, with a root / default disk named "rhel7disk" of 10G size. 
Now I would like to use ovirt.vm-infra role to deploy a couple of vms, but the root disk should be 50G:
```
   vms:
     - name: myvm
       disks:
        - size: 50GiB
          name: rhel7disk
       ...
```
That does not work, I end up with an _additional_ disk "myvm_rhel7disk". 

Let me try to formulate it as user story:
As an ovirt ansible user, I want to increase the disk size of disks specified by the template, so that I can avoid the additional hassle with ovirt_disks and so that I can directly use cloud init capabilities to resize partion and filesystem.

**Comment by kuwv** [comment]
From what I can tell this role includes the ovirt_disk module when it creates a VM. So it is capable of expanding the disk. It doesn't though because the vm_state_present task calls the ovirt_disk module with a custom name and preserves the existing disk.

https://github.com/oVirt/ovirt-ansible-vm-infra/blob/e875e6a5cfea8fbc20fdcdfeea6b32a288c1b36e/tasks/vm_state_present.yml#L23

Steps to perform a cloud-init with an expanded disk successfully:
1. Modify the referenced line to:
`name: "{{ item.1.name }}"`

2. Peform the cloud-init:
```
      - name: Instantiate VM
        include_role:
          name: ovirt.vm-infra
        vars:
          vms:
            - name: apache-vm
              tag: httpd
              profile: "{{ httpd_vm }}"
              cloud_init: "{{ cloud_init }}"
              state: 'running'
```
You still also have to know the name of the disk before hand but the disk name does work - at least on CentOS7 with Ansible-2.7.8.

This is the disk portion of the profile I used: 
```
      disks:
        - name: 'GlanceDisk-dd5e43a'
          size: 100GiB
          storage_domain: local_data_volume
          interface: virtio
```

**Comment by DanielFroehlich** [comment]
Thanks! Yes, that is the line. If I change it from
name: "{{ item.0.name }}_{{ item.1.name }}"
to
name: "{{ item.1.name }}"
the disk from the template is resized as expected.

So what would be the best way to implement this?
I do see two options:
#1: remove the vm-name prefix as suggested above
#2: add an additional attribute to the "disks" dictionary, e.g.
"nameAddVmPrefix=true|false" so you could enable/disable that prefxing.
Default to true to  keep current behavior.

I think #1 is a simplier and cleaner solution. The name you specify in the
dictionary is the actual name of the disk you get. Actually, i was
surprised is actually something different. If you want a Vm prefix, you
could specify it so. Downside: it would change existing behavior, maybe
breaking existing usages..

#2 does not break existing behavior but adds complexity, e.g. would need
additional documentation.

Happy to file a PR for either #1 or #2 - any comments?




Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243 Managing Directors:
Charles Cachera, Michael Cunningham, Michael O'Neill, Eric Shander

**Comment by kuwv** [comment]
I think either way is fine. But, if you go with option two I'd suggest a better name - such as addDiskHostnamePrefix.

A third option could be to add setPrimaryDiskSize and have a conditional block of code that checks if the parameter is set, locates the disk, and resizes the only if it is set. Then it can resize the primary disk when needed without changing the current setup.

The first option is easiest and works for now though.

**Comment by DanielFroehlich** [comment]
So with commit e78e43a, option#2 has been implemented, the name of the attribute is "name_prefix".
If you specify the name of the disk from the template with a NEW size, set "name_prefix=false", then the disk will be actually resized. 

I think this feature request can be closed, too!

**Comment by kuwv** [comment]
Can we confirm that this issue is resolved?

**Comment by DanielFroehlich** [comment]
Yes!

---
Sent from mobile, please excuse typos. Daniel.Froehlich@redhat.com, +49 176
10 24 84 33

Jesse P. Johnson <notifications@github.com> schrieb am Sa., 18. Mai 2019,
17:57:

**Comment by AlexGluck** [comment]
Anyone can say how to resize disk with your implementation in case create new vm or case modify exist vm?

**Comment by machacekondra** [comment]
We introduced new parameter `name_prefix`. So now if you have template with disk for example called `mydisk` and you want to resize it, you have to specify following `disks` variable:

```yaml
myprofile:
      name: myvm   
      disks:
        - size: 10GiB
          name_prefix: false
          name: mydisk
```

If the name of the disk match the name of the template disk it will be resized.

If you don't specify the `name_prefix` variable, the role will just try to create new disk, with VM's name prefix.
