### ISSUE TITLE
Issue with tasks Manage profile NICs and virtual machines NICs

### ISSUE THREAD

**Issue by erwstx** [oVirt/ovirt-ansible-vm-infra#56]
Hi,
Using this role, I cannot correctly create any NIC by setting a specific network.
I wonder why I don't find any example of playbook using this role and doing what I need on the Internet. Is it really working or I do not use the right syntax in my playbook ?

This is my playbook using this role. Each time I run it, it works, bu the network is not set on my NIC eth0

```
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: <censored>
    engine_user: <censored>
    engine_password: "<censored>"
    engine_cafile: <censored>

    debug_vm_create: yes

    classique_vm:
      cluster: <censored>
      datacenter: <censored>
      state: running
      storage_domain: <censored>
      template: <censored>
      clone: yes
      memory_guaranteed: 1MiB
      nics:
        - name: eth0
          network: <censored>
      cloud_init:
        host_name: <censored>
        root_password: '<censored>'
        authorized_ssh_keys: <censored>
        regenerate_ssh_keys: true
        nic_name: eth0
        nic_ip_address: <censored>
        nic_on_boot: true
        nic_boot_protocol: static
        nic_gateway: <censored>
        nic_netmask: <censored>
      cloud_init_persist: true

    vms:
      - name: <censored>
        profile: "{{ classique_vm }}"

  roles:
    - ovirt-vm-infra
```

**Comment by NoSuchCommand** [comment]
These two tasks seem very similar :
https://github.com/oVirt/ovirt-ansible-vm-infra/blob/969da98c4b85659956fd3b93c64cffefba33ab9a/tasks/vm_state_present.yml#L34-L47
https://github.com/oVirt/ovirt-ansible-vm-infra/blob/969da98c4b85659956fd3b93c64cffefba33ab9a/tasks/vm_state_present.yml#L49-L62
Does the 2nd one even make sense since it seems to rely on a `nics` property of the `vms` item itself, rather than the one inside its `profile` ?
Could this relate to #8 ?

**Comment by erwstx** [comment]
Hello friend,
This is normal I think. First task will create VNIC defined in your vm's profile (describe in your playbook), the second will create VNIC defined in your vm (describe in your playbook too)

This is the result of execution of these 2 tasks. 
It seems to be done, but the VNIC's network is not selected in RHV. Even if its name is !

```
TASK [ovirt-vm-infra : Manage profile NICs] ************************************
task path: /var/lib/awx/projects/rhv_installation_vm/roles/ovirt-vm-infra/tasks/vm_state_present.yml:34
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: <censored>
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587 `" && echo ansible-tmp-1540451713.68-227700303933587="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_nics.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3ZTM4h3/tmpeLpu_p TO /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587/ovirt_nics.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587/ /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587/ovirt_nics.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587/ovirt_nics.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1540451713.68-227700303933587/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item=[{u'profile': {u'datacenter': u'<censored>', u'storage_domain': u'<censored>', u'clone': True, u'memory_guaranteed': u'1MiB', u'cluster': u'<censored>', u'state': u'running', u'template': u'<censored>', u'cloud_init_persist': True, u'cloud_init': {u'authorized_ssh_keys': u'<censored>', u'nic_netmask': u'<censored>', u'nic_gateway': u'<censored>', u'regenerate_ssh_keys': True, u'nic_name': u'eth0', u'nic_ip_address': u'<censored>', u'host_name': u'<censored>', u'nic_boot_protocol': u'static', u'nic_on_boot': True, u'root_password': u'<censored>'}}, u'name': u'<censored>'}, {u'name': u'eth0', u'network': u'VLAN748/VLAN748'}]) => {
    "changed": true, 
    "diff": {
        "after": {}, 
        "before": {}
    }, 
    "id": "0ca50c35-247f-4398-9970-dba39777dbe9", 
    "invocation": {
        "module_args": {
            "fetch_nested": false, 
            "interface": null, 
            "mac_address": null, 
            "name": "eth0", 
            "nested_attributes": [], 
            "network": "VLAN748/VLAN748", 
            "poll_interval": 3, 
            "profile": null, 
            "state": "present", 
            "template": null, 
            "timeout": 180, 
            "vm": "<censored>", 
            "wait": true
        }
    }, 
    "item": [
        {
            "name": "<censored>", 
            "profile": {
                "clone": true, 
                "cloud_init": {
                    "authorized_ssh_keys": "<censored>", 
                    "host_name": "<censored>", 
                    "nic_boot_protocol": "static", 
                    "nic_gateway": "<censored>", 
                    "nic_ip_address": "<censored>", 
                    "nic_name": "eth0", 
                    "nic_netmask": "<censored>", 
                    "nic_on_boot": true, 
                    "regenerate_ssh_keys": true, 
                    "root_password": "<censored>"
                }, 
                "cloud_init_persist": true, 
                "cluster": "<censored>", 
                "datacenter": "<censored>", 
                "memory_guaranteed": "1MiB", 
                "state": "running", 
                "storage_domain": "<censored>", 
                "template": "<censored>"
            }
        }, 
        {
            "name": "eth0", 
            "network": "VLAN748/VLAN748"
        }
    ], 
    "nic": {
        "href": "/ovirt-engine/api/vms/6efb4975-baac-4fc4-bbba-3162dc945c28/nics/0ca50c35-247f-4398-9970-dba39777dbe9", 
        "id": "0ca50c35-247f-4398-9970-dba39777dbe9", 
        "interface": "virtio", 
        "linked": true, 
        "mac": {
            "address": "00:1a:4a:16:01:9d"
        }, 
        "name": "eth0", 
        "network_filter_parameters": [], 
        "plugged": true, 
        "reported_devices": [], 
        "statistics": [], 
        "vm": {
            "href": "/ovirt-engine/api/vms/6efb4975-baac-4fc4-bbba-3162dc945c28", 
            "id": "6efb4975-baac-4fc4-bbba-3162dc945c28"
        }
    }
}
Read vars_file 'xorc_password.yml'


TASK [ovirt-vm-infra : Manage virtual machines NICs] ***************************
task path: /var/lib/awx/projects/rhv_installation_vm/roles/ovirt-vm-infra/tasks/vm_state_present.yml:49

Read vars_file 'xorc_password.yml'
```

**Comment by machacekondra** [comment]
It's possible to have more networks and vnic profiles with same names, so you must enter both network and vnic profile. I can add a support to auto select profile in case the network has just one. If you would like to, and I will definitelly create example playbook for this. So for now to make it work do:

```yaml
classique_vm:
      cluster: <censored>
      datacenter: <censored>
      state: running
      storage_domain: <censored>
      template: <censored>
      clone: yes
      memory_guaranteed: 1MiB
      nics:
        - name: eth0
          network: <censored>
          profile: <censored>
```
