### ISSUE TITLE
Facts persist between plays in the same playbook, causing aberrant behavior during complex runs

### ISSUE THREAD

**Issue by solacelost** [oVirt/ovirt-ansible-vm-infra#92]
### Description
If a playbook creates some VMs using the role, then later sets the state of one to absent before re-including the role in the same playbook, the VMs will be recreated immediately after deletion.
##### Context
I am currently using the role with a complex playbook that needs to define lots of VMs, but one of them is ephemeral and required for use in other playbook steps and nothing else. It is created as part of the original provisioning, then later deleted alone. It was deleting, but then being recreated immediately.
### Examples
Example my_vms.yml:
```yaml
---
my_vms:
  - name: vm1
    state: running
    cluster: mycluster
    domain: localdomain.org
    template: mytemplate
    memory: 16GiB
    memory_guaranteed: 8GiB
    cores: 2
    nics:
      - name: nic1
        network: ovirtmgmt
        profile: ovirtmgmt
    disks:
      - name: data
        storage_domain: vmstore
        interface: virtio
        size: 10GiB

  - name: vm2
    state: running
    cluster: mycluster
    domain: localdomain.org
    template: mytemplate
    memory: 16GiB
    memory_guaranteed: 8GiB
    cores: 2
    nics:
      - name: nic1
        network: ovirtmgmt
        profile: ovirtmgmt
    disks:
      - name: data
        storage_domain: vmstore
        interface: virtio
        size: 20GiB
```
Example playbook:
```yaml
---
- name: Create two vms
  hosts: localhost
  vars_files:
    - '{{ playbook_dir }}/my_vms.yml'
  vars:
    wait_for_ip: true
    vms: '{{ my_vms }}'
  roles:
    - ovirt.vm-infra

- name: Do some stuff on vm2
  hosts: vm2
  tasks:
    - setup:
    - package:
        name: httpd
        state: latest

# Notional do other stuff on other vms, related to the temporary thing on vm2

- name: Remove vm2
  hosts: localhost
  vars_files:
    - '{{ playbook_dir }}/my_vms.yml'
  vars:
    vms:
      - '{{ my_vms | selectattr("name", "==", "vm2") | first | combine({"state":"absent"}) }}'
  roles:
    - ovirt.vm-infra
```
### Expected result
The cluster should have vm1 on it, not vm2
### Actual result
vm1 and vm2 exist, vm2 has been deleted and then rebuilt from the template.
### Cause
Because create_vms and create_sensitive_vms are set as facts, they persist between plays in the same playbook. The conditional import of vm_state_present then results in the inclusion of create_vms.yml with each vm in the create_vms list.

I have a commit ready for this issue, I am filing for context.
